name: Docker Build
description: Build a Docker image
inputs:
  path_dockerfile:
    description: "Path to the Dockerfile"
    required: false
    default: "Dockerfile"
  image_name:
    description: "Name for the generated Docker image"
    required: true
  tag_name:
    description: "Tag to be added to the final image"
    required: false

runs:
  using: composite
  steps:
    - name: Build Docker image
      shell: bash
      run: |

        if [ -z "${{ inputs.path_dockerfile }}" ]; then
            PATH_DOCKERFILE=$(date +%s)
        else
            PATH_DOCKERFILE="${{ inputs.path_dockerfile }}"
        fi
        echo "PATH_DOCKERFILE=$PATH_DOCKERFILE" >> $GITHUB_ENV

        if [ -z "${{ inputs.image_name }}" ]; then
            IMAGE_ENAME=$(date +%s)
        else
            IMAGE_ENAME="${{ inputs.image_name }}"
        fi
        echo "IMAGE_ENAME=$IMAGE_ENAME" >> $GITHUB_ENV

        if [ -z "${{ inputs.tag_name }}" ]; then
            TAG=$(date +%s)
        else
            TAG="${{ inputs.tag_name }}"
        fi
        echo "TAG=$TAG" >> $GITHUB_ENV
        
        # Construct the full image name
        IMAGE_NAME="${{ inputs.image_name }}:$TAG"
        echo "DOCKER_IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

        # Build the Docker image
        docker build . --file "${{ inputs.path_dockerfile }}" --tag "$IMAGE_NAME"
