name: Docker Build
description: Build a Docker image
inputs:
  path_dockerfile:
    description: "Path to the Dockerfile"
    required: false
    default: "Dockerfile"
  image_name:
    description: "Name for the generated Docker image"
    required: true
  tag_name:
    description: "Tag to be added to the final image"
    required: false

runs:
  using: composite
  steps:
    - name: Build Docker image
      shell: bash
      run: |
        # Determine the tag
        if [ -z "${{ inputs.tag_name }}" ]; then
            echo "TAG=$(date +%s)" >> $GITHUB_ENV
        else
            echo "TAG=${{ inputs.tag_name }}" >> $GITHUB_ENV
        fi

        # Construct the full image name
        IMAGE_NAME="${{ inputs.image_name }}:${{ env.TAG }}"
        echo "DOCKER_IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

        # Build the Docker image
        docker build . --file "${{ inputs.path_dockerfile }}" --tag "$IMAGE_NAME"
