name: Build
description: Build application with Maven and create a new Docker image
inputs:
  dockerfile_path:
    description: "Path to the Dockerfile"
    required: false
    default: "src/main/docker/Dockerfile.jvm" # Update default path if needed
runs:
  using: composite
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml
    
    - name: Create new Docker image
      run: docker build . --file ${{ inputs.dockerfile_path }} --tag academy:$(date +%s)
    
    - name: List Docker images
      run: docker images
