name: Docker Hub Action

description: A GitHub Action to build and push Docker images to Docker Hub.

inputs:
  dockerhub_username:
    description: 'Docker Hub username'
    required: true
  dockerhub_token:
    description: 'Docker Hub access token'
    required: true
  path_dockerfile:
    description: 'Path to the Dockerfile'
    required: true
  image_name:
    description: 'Name of the Docker image'
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_token }}

    - name: Build Docker image
      shell: bash
      run: |
        docker build . --file "${{ inputs.path_dockerfile }}" --tag "${{ inputs.image_name }}"

    - name: Re-tag docker image
      shell: bash
      run: |
        SOURCE_IMAGE="${{ inputs.image_name }}"
        TAGGED_IMAGE="${{ inputs.dockerhub_username }}/${SOURCE_IMAGE}:latest"
        docker tag "$SOURCE_IMAGE" "$TAGGED_IMAGE"

    - name: Push Docker image
      shell: bash
      run: |
        TAGGED_IMAGE="${{ inputs.dockerhub_username }}/${{ inputs.image_name }}:latest"
        docker push "$TAGGED_IMAGE"
