name: ci

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ joaofranciscomonteiro175 }} 
      DOCKERHUB_TOKEN: ${{ ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII6+jkB7lHBzcdB29auXUL0kPo2s8HUDu/G5ijHDiOkH jfcmo98647@gmail.com }}  
      DOCKERFILE_PATH: 'src/main/docker/Dockerfile.jvm'  
      IMAGE_NAME: 'academy'  

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Create new Docker image
        shell: bash  
        run: docker build . --file ${{ env.dockerfile_path }} --tag academy:$(date +%s)

      - name: Tag Docker image
        run: |
          IMAGE_NAME=${{ env.image_name }}
          DOCKER_USERNAME=${{ env.DOCKERHUB_USERNAME }}
          TAGGED_IMAGE="${DOCKER_USERNAME}/${IMAGE_NAME}:latest"
          docker tag academy:$(date +%s) "$TAGGED_IMAGE"

      - name: Push Docker image
        run: |
          IMAGE_NAME=${{ env.image_name }}
          DOCKER_USERNAME=${{ env.DOCKERHUB_USERNAME }}
          TAGGED_IMAGE="${DOCKER_USERNAME}/${IMAGE_NAME}:latest"
          docker push "$TAGGED_IMAGE"