name: Docker Hub Action

description: A GitHub Action to build and push Docker images to Docker Hub.

inputs:
  dockerhub_username:
    description: 'Docker Hub username'
    required: true
  dockerhub_token:
    description: 'Docker Hub access token'
    required: true
  path_dockerfile:
    description: 'Path to the Dockerfile'
    required: true
  image_name:
    description: 'Name of the Docker image'
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_token }}

    - name: Create new Docker image
      run: docker build . --file ${{ inputs.path_dockerfile }} --tag academy:$(date +%s)

    - name: Tag Docker image
      run: |
        IMAGE_NAME=${{ inputs.image_name }}
        TAGGED_IMAGE="${{ inputs.dockerhub_username }}/${IMAGE_NAME}:latest"
        docker tag academy:$(date +%s) "$TAGGED_IMAGE"

    - name: Push Docker image
      run: |
        IMAGE_NAME=${{ inputs.image_name }}
        TAGGED_IMAGE="${{ inputs.dockerhub_username }}/${IMAGE_NAME}:latest"
        docker push "$TAGGED_IMAGE"
