name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: joaofcmont/academy/.github/actions/maven_build@main
    - uses: joaofcmont/academy/.github/actions/docker_build@main

